# Generated by Django 2.2.4 on 2019-08-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continentes', '0001_initial'),
        ('paises', '0003_pais_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='continente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continentes.Continente'),
            preserve_default=False,
        ),
    ]
