# Generated by Django 2.2.4 on 2019-08-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moedas', '0002_auto_20190807_1519'),
        ('jogadores', '0002_auto_20190807_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('compra', models.DecimalField(decimal_places=2, default=0, max_digits=16, max_length=16)),
                ('venda', models.DecimalField(decimal_places=2, default=0, max_digits=16, max_length=16)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.Jogador')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moedas.Moeda')),
            ],
        ),
    ]
