# Generated by Django 2.2.4 on 2019-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_auto_20190807_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='foto',
            field=models.ImageField(blank=True, upload_to='equipes'),
        ),
    ]
