# Generated by Django 2.2.4 on 2019-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0003_equipe_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nome_conhecido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
