# Generated by Django 2.2.4 on 2019-08-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0004_equipe_nome_conhecido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome_conhecido'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
    ]
