# Generated by Django 2.2.4 on 2019-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0006_equipe_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
