# Generated by Django 2.2.4 on 2019-08-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisoes', '0001_initial'),
        ('equipes', '0007_equipe_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='campeonato',
        ),
        migrations.AddField(
            model_name='equipe',
            name='divisao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='divisoes.Divisao'),
            preserve_default=False,
        ),
    ]
