# Generated by Django 2.2.4 on 2019-08-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0008_auto_20190816_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='divisao',
        ),
    ]
