# Generated by Django 2.2.4 on 2019-08-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisoes', '0001_initial'),
        ('equipes', '0009_remove_equipe_divisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='divisao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='divisoes.Divisao'),
            preserve_default=False,
        ),
    ]
