# Generated by Django 2.2.4 on 2019-08-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(help_text='Informa a hora em que o evento vai ocorrer'),
        ),
    ]
