# Generated by Django 2.2.4 on 2019-08-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190817_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='divisao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='rodada',
        ),
    ]
