# Generated by Django 2.2.4 on 2019-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20190817_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='placar_coluna_1',
            field=models.PositiveIntegerField(blank=True, help_text='Indica o placar do mandante', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='placar_coluna_2',
            field=models.PositiveIntegerField(blank=True, help_text='Indica o placar do visitante', max_length=2, null=True),
        ),
    ]
