# Generated by Django 2.2.4 on 2019-08-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20190817_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='placar_coluna_1',
            field=models.PositiveIntegerField(blank=True, help_text='Indica o placar do mandante', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='placar_coluna_2',
            field=models.PositiveIntegerField(blank=True, help_text='Indica o placar do visitante', null=True),
        ),
    ]
