# Generated by Django 2.2.4 on 2019-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20190817_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(help_text='Informa a data e hora em que o evento vai ocorrer'),
        ),
    ]
