# Generated by Django 2.2.4 on 2019-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informa o nome da Divisão', max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Informa se está ativo ou não')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
