# Generated by Django 2.2.4 on 2019-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Indica o número do concurso', unique=True)),
                ('abertura', models.DateTimeField(help_text='Abertura das apostas')),
                ('encerramento', models.DateTimeField(help_text='Encerramento das apostas')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o Concurso ainda aceita apostas.')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
