# Generated by Django 2.2.4 on 2019-08-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='num_max_jogos',
            field=models.PositiveIntegerField(default=14, help_text='Quantidade de máxima de joos nesse concurso'),
        ),
    ]
