# Generated by Django 2.2.4 on 2019-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_auto_20190816_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'ordering': ['-ano', 'nome']},
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='nome',
            field=models.CharField(help_text='Nome do Campeonato', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='campeonato',
            unique_together={('nome', 'ano')},
        ),
    ]
