# Generated by Django 2.2.4 on 2019-08-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esportes', '0002_auto_20190817_1222'),
        ('campeonatos', '0003_auto_20190816_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='esporte',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='esportes.Esporte'),
            preserve_default=False,
        ),
    ]
