# Generated by Django 2.2.4 on 2019-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_pais_foto'),
        ('campeonatos', '0004_campeonato_esporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paises.Pais'),
            preserve_default=False,
        ),
    ]
