# Generated by Django 2.2.4 on 2019-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='numero',
            field=models.PositiveIntegerField(help_text='Indica o número da Rodada'),
        ),
    ]
