# Generated by Django 2.2.4 on 2019-08-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moeda',
            options={'ordering': ['nome'], 'verbose_name': 'Moeda', 'verbose_name_plural': 'Moedas'},
        ),
    ]
