# Generated by Django 2.2.4 on 2019-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esporte',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='esporte',
            name='nome',
            field=models.CharField(help_text='Indica o nome do esporte', max_length=50, unique=True),
        ),
    ]
